# Generated by Django 2.2.1 on 2019-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190623_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
