# Generated by Django 2.2.1 on 2019-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190623_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
