# Generated by Django 2.2.1 on 2019-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190623_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
